### ISSUE TITLE
RancherOS / custom rules

### ISSUE THREAD

**Issue by vitobotta** [devrt/docker-container-firewall#1]
Hi! I am looking to use RancherOS for my Kubernetes nodes, and since everything in RancherOS runs as a container I was looking for a container based firewall, so I found this. I like that it is very easy to open just selected ports, but I also would need to add rules that allow all traffic between from the IPs of the other nodes of the Kubernetes cluster. Would you mind giving me an example of how to modify the script and the env variables to configure access by IP? I am new to this.

Thanks in advance!

**Comment by yosuke** [comment]
Hi,
It seems RancherOS officially support network policy customization by using their extension.
https://rancher.com/docs/rancher/v1.4/en/rancher-services/network-policy/
Have you tried this?
